add_subdirectory( grid )
add_subdirectory( heap )
ot_add_test_subdirectory( polymesh QHULL )
ot_add_test_subdirectory( polymesh_compute_voronoi TRIANGLE )
add_subdirectory( polymesh_is_point_inside )
ot_add_test_subdirectory( trimesh QHULL )
ot_add_test_subdirectory( mesh_convex_hull QHULL )
add_subdirectory( t4mesh_compute_mesh_quality )
add_subdirectory( t4mesh_t4mesh )
ot_add_test_subdirectory( t4mesh_xml TINYXML )
add_subdirectory( t4mesh_mel )

