add_subdirectory( chain )
add_subdirectory( jacobian_assembly )
ot_add_test_subdirectory( nonlinear_solver TINYXML )
ot_add_test_subdirectory( joint_parameters TINYXML )
ot_add_test_subdirectory( compute_weighted_diff TINYXML )
ot_add_test_subdirectory( set_default_joints TINYXML )
ot_add_test_subdirectory( ik_io TINYXML )
